import type { Level, Character, Constraint, SeatAttr } from './types';
import { EXPANSION_LEVELS, rebalanceStoryLevels } from './generatedLevels';
import {
  busLayout,
  classroomLayout,
  coffeeLayout,
  restaurantLayout,
  theaterLayout,
  airportLayout,
  weddingLayout,
  cruiseLayout,
} from './layouts';

const want = (attr: SeatAttr): Constraint => ({ type: 'attr', attr });
const avoid = (attr: SeatAttr): Constraint => ({ type: 'noAttr', attr });
const beside = (who: string): Constraint => ({ type: 'beside', who });
const notNear = (who: string): Constraint => ({ type: 'notBeside', who });

function ch(
  id: string,
  name: string,
  hue: number,
  trait: string,
  constraints: Constraint[],
): Character {
  return { id, name, hue, trait, constraints };
}

const BASE_LEVELS: Level[] = [
  {
    id: 1, env: 'bus', title: 'Field Trip Frenzy', hostName: 'Mr. Pebble',
    intro: 'First day field trip! Six kids, one wobbly bus. Everybody wants the perfect seat... can you make peace before we hit the road?',
    outro: "Buckle up — the bus rolls off humming with happy campers. You're a natural seat whisperer!",
    seats: busLayout,
    characters: [
      ch('mika', 'Mika', 200, 'Loves the view', [want('window'), want('front')]),
      ch('lola', 'Lola', 330, 'Front aisle fan', [want('aisle'), want('front')]),
      ch('theo', 'Theo', 30, 'Long legs', [want('legroom')]),
      ch('sam', 'Sam', 120, 'Middle aisle', [want('aisle'), avoid('front'), avoid('back')]),
      ch('isa', 'Isa', 270, 'Back window dreamer', [want('window'), want('back')]),
      ch('ben', 'Ben', 90, 'Middle window dreamer', [want('window'), avoid('front'), avoid('back')]),
    ],
  },
  {
    id: 2, env: 'classroom', title: 'Pop Quiz Panic', hostName: 'Ms. Quill',
    intro: 'Surprise quiz today! Seat the class so everyone can focus — quiet kids in the back, window dreamers by the glass.',
    outro: 'Pencils down — a perfectly peaceful classroom. Ms. Quill gives you a gold star.',
    seats: classroomLayout,
    characters: [
      ch('ada', 'Ada', 280, 'Front-row star', [want('front'), want('window')]),
      ch('omar', 'Omar', 130, 'Middle front desk', [want('front'), avoid('window'), avoid('quiet')]),
      ch('zoe', 'Zoe', 320, 'Loves the front', [want('front'), want('quiet')]),
      ch('nina', 'Nina', 180, 'Sunny window gazer', [want('back'), want('window')]),
      ch('pip', 'Pip', 50, 'Middle back desk', [want('back'), avoid('window'), avoid('quiet')]),
      ch('rex', 'Rex', 20, 'Needs quiet', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 3, env: 'coffee', title: 'Coffee Shop Chaos', hostName: 'Barista Bea',
    intro: 'Morning rush at The Cozy Bean! Some crave music, some need quiet, some just want sunlight and a latte.',
    outro: 'Steam rises, jazz plays, everyone sips happily. The Cozy Bean has never been cozier.',
    seats: coffeeLayout,
    characters: [
      ch('milo', 'Milo', 30, 'Sun seeker', [want('sunlight')]),
      ch('ivy', 'Ivy', 150, 'Shady window watcher', [want('window'), avoid('sunlight')]),
      ch('rae', 'Rae', 200, 'Quiet reader', [want('quiet'), want('front')]),
      ch('vee', 'Vee', 330, 'Back quiet table', [want('quiet'), want('back')]),
      ch('dex', 'Dex', 110, 'Music lover', [want('music'), want('front')]),
      ch('cole', 'Cole', 240, 'Always hungry', [want('food'), want('back')]),
    ],
  },
  {
    id: 4, env: 'restaurant', title: 'Anniversary Dinner', hostName: 'Chef Romeo',
    intro: 'A big celebration at Bella Trattoria! Romantics want the quiet window booth, foodies want a front-row seat to the kitchen.',
    outro: 'Glasses clink, candles flicker — a flawless evening. Bravissimo, you seating maestro!',
    seats: restaurantLayout,
    characters: [
      ch('gia', 'Gia', 340, 'Wants romance', [want('quiet'), want('window'), want('front')]),
      ch('leo', 'Leo', 210, 'Back window booth', [want('quiet'), want('window'), want('back')]),
      ch('max', 'Max', 30, 'Kitchen watcher', [want('food'), avoid('aisle')]),
      ch('tom', 'Tom', 90, 'Aisle foodie', [want('food'), want('aisle')]),
      ch('lia', 'Lia', 280, 'Sun-lover', [want('sunlight'), want('music')]),
      ch('sky', 'Sky', 180, 'Soft music seat', [want('music'), avoid('sunlight')]),
    ],
  },
  {
    id: 5, env: 'theater', title: 'Movie Night Mayhem', hostName: 'Usher Pip',
    intro: 'Premiere night! Some want the back row, some the front, someone needs the aisle, and someone snuck in popcorn...',
    outro: 'Lights dim, the show begins, and every seat is perfect. Roll credits — you nailed it!',
    seats: theaterLayout,
    characters: [
      ch('roo', 'Roo', 120, 'Needs an exit', [want('aisle'), want('front')]),
      ch('nox', 'Nox', 250, 'Back-row cool', [want('back'), want('aisle')]),
      ch('dot', 'Dot', 330, 'Close to the screen', [want('front'), beside('roo')]),
      ch('mae', 'Mae', 190, 'Front but not by Roo', [want('front'), notNear('roo')]),
      ch('finn', 'Finn', 30, 'Brought popcorn', [want('food')]),
      ch('sol', 'Sol', 50, 'Likes it calm', [want('quiet'), avoid('aisle'), avoid('food')]),
    ],
  },
  {
    id: 6, env: 'bus', title: 'Last Bus Home', hostName: 'Driver Dot',
    intro: 'Late night, one last bus. Tired travelers, picky preferences. Get everyone settled before the doors close!',
    outro: 'Engine hums, city lights blur past windows. Everyone dozes off happily — good night!',
    seats: busLayout,
    characters: [
      ch('di', 'Di', 120, 'Up front please', [want('window'), want('front')]),
      ch('art', 'Art', 200, 'Window napper', [want('window')]),
      ch('bee', 'Bee', 330, 'Art’s partner', [beside('art')]),
      ch('cy', 'Cy', 30, 'Tall traveler', [want('legroom')]),
      ch('eli', 'Eli', 270, 'Aisle walker', [want('aisle')]),
      ch('fay', 'Fay', 90, 'Window dreamer', [want('window')]),
    ],
  },
  {
    id: 7, env: 'classroom', title: 'Science Fair Setup', hostName: 'Mr. Bunsen',
    intro: 'Science fair day! Partners stay together, quiet thinkers get their calm corner, builders take the back.',
    outro: 'Volcanoes erupt, robots whir — a brilliant fair, and not a single squabble. Eureka!',
    seats: classroomLayout,
    characters: [
      ch('uma', 'Uma', 280, 'Window dreamer', [want('window'), want('front')]),
      ch('jo', 'Jo', 130, 'Uma’s partner', [beside('uma')]),
      ch('ned', 'Ned', 320, 'Needs focus', [want('quiet'), want('front')]),
      ch('pia', 'Pia', 50, 'Back-row builder', [want('back'), want('window')]),
      ch('rin', 'Rin', 180, 'Quiet genius', [want('quiet')]),
      ch('koa', 'Koa', 20, 'Loud inventor', [want('back')]),
    ],
  },
  {
    id: 8, env: 'coffee', title: 'Rainy Day Refuge', hostName: 'Barista Bea',
    intro: 'Rain outside, warmth inside. The cafe fills with cozy regulars — each with very particular tastes.',
    outro: 'Rain taps the glass, mugs steam, and every regular is right where they belong. Bliss.',
    seats: coffeeLayout,
    characters: [
      ch('wen', 'Wen', 30, 'Watches the rain', [want('window'), want('sunlight')]),
      ch('hal', 'Hal', 200, 'Wen’s friend', [beside('wen')]),
      ch('joy', 'Joy', 110, 'Hums to music', [want('music'), want('front')]),
      ch('ash', 'Ash', 240, 'Snack attack', [want('food'), want('back')]),
      ch('kit', 'Kit', 330, 'Quiet knitter', [want('quiet'), want('front')]),
      ch('bex', 'Bex', 150, 'Quiet reader', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 9, env: 'airport', title: 'Holiday Airport Rush', hostName: 'Gate Agent Joon',
    intro: 'The holiday rush hits Gate 12! Window-watchers, leg-stretchers, and snackers all need the right spot before boarding.',
    outro: 'Boarding call! Everyone found their perfect seat with time to spare. Safe travels, travelers!',
    seats: airportLayout,
    characters: [
      ch('nia', 'Nia', 200, 'Quiet window watcher', [want('window'), want('quiet')]),
      ch('guy', 'Guy', 330, 'Nia’s travel buddy', [beside('nia')]),
      ch('tex', 'Tex', 30, 'Needs leg room', [want('legroom')]),
      ch('duke', 'Duke', 90, 'Loves a snack & a tune', [want('food'), want('music')]),
      ch('mae2', 'Mae', 280, 'Hungry flyer', [want('food')]),
      ch('pam', 'Pam', 150, 'Afraid of dogs', [want('aisle'), notNear('duke')]),
    ],
  },
  {
    id: 10, env: 'wedding', title: 'Wedding Reception Drama', hostName: 'Planner Posy',
    intro: 'The reception begins! Garden lovers want the window table, dancers want the music, and two cousins must NOT sit together.',
    outro: 'Cake cut, toasts made, not one squabble — a fairytale reception. You saved the day!',
    seats: weddingLayout,
    characters: [
      ch('rose', 'Rose', 330, 'Quiet garden view', [want('window'), want('quiet')]),
      ch('jack', 'Jack', 210, 'Rose’s partner', [beside('rose')]),
      ch('amy', 'Amy', 110, 'Lives to dance', [want('music')]),
      ch('sol2', 'Sol', 50, 'Loves the sun', [want('sunlight')]),
      ch('nan', 'Nan', 30, 'Here for the cake', [want('food'), want('back')]),
      ch('pip2', 'Pip', 180, 'Cousin feud', [want('food'), want('front'), notNear('amy')]),
    ],
  },
  {
    id: 11, env: 'cruise', title: 'Cruise Ship Lounge', hostName: 'Captain Coral',
    intro: 'Welcome aboard! Sun-deck loungers, ocean gazers, pool-bar dancers — everyone wants their dream chair.',
    outro: 'Waves roll, the band plays, and the whole deck is content. Smooth sailing ahead!',
    seats: cruiseLayout,
    characters: [
      ch('sunny', 'Sunny', 50, 'Sun-deck lounger', [want('sunlight')]),
      ch('wave', 'Wave', 200, 'Ocean gazer', [want('window')]),
      ch('dj', 'DJ', 110, 'Pool-bar dancer', [want('music')]),
      ch('finn2', 'Finn', 30, 'Buffet bound', [want('food')]),
      ch('cal', 'Cal', 280, 'Naps in quiet', [want('quiet'), want('front')]),
      ch('nora', 'Nora', 330, 'Cal’s friend', [beside('cal')]),
    ],
  },
  {
    id: 12, env: 'airport', title: 'Red-Eye Reshuffle', hostName: 'Gate Agent Joon',
    intro: 'A delayed red-eye means picky passengers. Window nappers, snackers, and one nervous flyer who avoids the loud crowd.',
    outro: 'Wheels up at last — a cabin full of contented passengers. You’re cleared for takeoff!',
    seats: airportLayout,
    characters: [
      ch('ria', 'Ria', 200, 'Window napper', [want('window'), want('quiet')]),
      ch('bo', 'Bo', 330, 'Ria’s seatmate', [beside('ria')]),
      ch('len', 'Len', 30, 'Stretches out', [want('legroom')]),
      ch('dax', 'Dax', 90, 'Snack & beats', [want('food'), want('music')]),
      ch('moe', 'Moe', 280, 'Munchies', [want('food')]),
      ch('val', 'Val', 150, 'Avoids the noisy one', [want('aisle'), notNear('dax')]),
    ],
  },
  {
    id: 13, env: 'wedding', title: 'Garden Vows', hostName: 'Planner Posy',
    intro: 'An outdoor wedding! Quiet aunts by the window, dancers near the band, and the bickering uncles kept apart.',
    outro: 'Petals fall, music swells — a flawless celebration of love. Truly magical seating!',
    seats: weddingLayout,
    characters: [
      ch('iris', 'Iris', 200, 'Quiet aunt', [want('quiet'), want('window')]),
      ch('leo2', 'Leo', 130, 'Iris’s partner', [beside('iris')]),
      ch('bea2', 'Bea', 110, 'Dances all night', [want('music')]),
      ch('max2', 'Max', 50, 'Sun & song', [want('sunlight'), want('music')]),
      ch('gus', 'Gus', 30, 'Loves the feast', [want('food'), want('back')]),
      ch('dot2', 'Dot', 280, 'Uncle feud', [want('food'), want('front'), notNear('bea2')]),
    ],
  },
  {
    id: 14, env: 'cruise', title: 'Sunset Deck Party', hostName: 'Captain Coral',
    intro: 'Golden hour on the top deck! Ocean lovers, dancers, and a guest who can’t bear to be near the loud DJ.',
    outro: 'The sun melts into the sea as everyone relaxes in the perfect spot. Bon voyage!',
    seats: cruiseLayout,
    characters: [
      ch('pearl', 'Pearl', 200, 'Ocean gazer', [want('window'), want('sunlight')]),
      ch('shell', 'Shell', 330, 'Pearl’s pal', [beside('pearl')]),
      ch('bay', 'Bay', 110, 'Loud DJ', [want('music')]),
      ch('reef', 'Reef', 30, 'Loves the bar bites', [want('food'), want('music')]),
      ch('moss', 'Moss', 280, 'Hates the noise', [want('quiet'), want('front'), notNear('bay')]),
      ch('fern', 'Fern', 150, 'Peace & quiet', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 15, env: 'coffee', title: 'Book Club Brews', hostName: 'Barista Bea',
    intro: 'The Cozy Bean hosts book club tonight. Sun readers, quiet note-takers, and pastry hunters all need their favorite corners.',
    outro: 'Pages turn, cups clink, and every reader has the perfect little nook.',
    seats: coffeeLayout,
    characters: [
      ch('tara', 'Tara', 45, 'Sunlit reader', [want('window'), want('sunlight')]),
      ch('mo', 'Mo', 210, 'Rain watcher', [want('window'), avoid('sunlight')]),
      ch('jazz', 'Jazz', 120, 'Front-row music fan', [want('music'), want('front')]),
      ch('bun', 'Bun', 20, 'Back table snacker', [want('food'), want('back')]),
      ch('quill', 'Quill', 280, 'Quiet note-taker', [want('quiet'), want('front')]),
      ch('noe', 'Noe', 330, 'Back-corner thinker', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 16, env: 'airport', title: 'Gate Change Shuffle', hostName: 'Gate Agent Joon',
    intro: 'A sudden gate change sends everyone scrambling. Help the travelers settle before the boarding screen updates again.',
    outro: 'The gate quiets down, bags are tucked away, and every boarding pass holder is smiling.',
    seats: airportLayout,
    characters: [
      ch('elsa', 'Elsa', 200, 'Quiet window flyer', [want('window'), want('quiet')]),
      ch('kit2', 'Kit', 330, 'Elsa’s seatmate', [want('window'), beside('elsa')]),
      ch('stretch', 'Stretch', 30, 'Long stride', [want('legroom')]),
      ch('maya', 'Maya', 150, 'Aisle planner', [want('aisle'), avoid('legroom')]),
      ch('snack', 'Snack', 50, 'Snack stop', [want('food'), avoid('music')]),
      ch('melody', 'Melody', 110, 'Snack and songs', [want('food'), want('music')]),
    ],
  },
  {
    id: 17, env: 'restaurant', title: 'Chef’s Tasting Table', hostName: 'Chef Romeo',
    intro: 'The tasting menu is ready. Window dreamers, kitchen watchers, and music lovers all have strong opinions tonight.',
    outro: 'Every course lands beautifully, and the room hums with happy dinner chatter.',
    seats: restaurantLayout,
    characters: [
      ch('lumi', 'Lumi', 340, 'Front booth romantic', [want('window'), want('quiet'), want('front')]),
      ch('oak', 'Oak', 210, 'Back booth poet', [want('window'), want('quiet'), want('back')]),
      ch('basil', 'Basil', 90, 'Kitchen watcher', [want('food'), avoid('aisle')]),
      ch('vera', 'Vera', 30, 'Aisle foodie', [want('food'), want('aisle')]),
      ch('song', 'Song', 120, 'Soft music only', [want('music'), avoid('sunlight')]),
      ch('dawn', 'Dawn', 50, 'Bright live music', [want('music'), want('sunlight')]),
    ],
  },
  {
    id: 18, env: 'classroom', title: 'Art Class Arrangement', hostName: 'Ms. Quill',
    intro: 'Paint pots are open and everyone needs just the right desk: sunny views, quiet focus, and enough room for ideas.',
    outro: 'Brushes swish, colors glow, and the whole class settles into a masterpiece of calm.',
    seats: classroomLayout,
    characters: [
      ch('prim', 'Prim', 300, 'Window artist', [want('front'), want('window')]),
      ch('fin2', 'Fin', 140, 'Middle helper', [want('front'), avoid('window'), avoid('quiet')]),
      ch('hush', 'Hush', 220, 'Quiet front focus', [want('front'), want('quiet')]),
      ch('gleam', 'Gleam', 55, 'Sunny back desk', [want('back'), want('window'), want('sunlight')]),
      ch('rowan', 'Rowan', 20, 'Back-row mixer', [want('back'), avoid('window'), avoid('quiet')]),
      ch('murph', 'Murph', 180, 'Quiet back painter', [want('back'), want('quiet')]),
    ],
  },
  {
    id: 19, env: 'cruise', title: 'Moonlit Deck Puzzle', hostName: 'Captain Coral',
    intro: 'Evening settles over the ship. Ocean gazers, late-night snackers, and quiet stargazers need their deck chairs.',
    outro: 'The moon rises, the deck glows, and everyone finds their perfect place at sea.',
    seats: cruiseLayout,
    characters: [
      ch('azul', 'Azul', 200, 'Sunny ocean view', [want('window'), want('sunlight')]),
      ch('mist', 'Mist', 330, 'Shady ocean view', [want('window'), avoid('sunlight')]),
      ch('beat', 'Beat', 110, 'Music listener', [want('music'), avoid('food')]),
      ch('nib', 'Nib', 30, 'Buffet dancer', [want('music'), want('food')]),
      ch('hush2', 'Hush', 260, 'Front quiet chair', [want('quiet'), want('front')]),
      ch('lune', 'Lune', 150, 'Back quiet chair', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 20, env: 'bus', title: 'Bus Ride Trouble', hostName: 'Driver Dot',
    intro: 'The after-school bus is packed with tired riders. Window watchers, aisle planners, and one very tall passenger all need help.',
    outro: 'The bus pulls away smoothly, and every rider has a seat that feels just right.',
    seats: busLayout,
    characters: [
      ch('mira20', 'Mira', 210, 'Front window calm', [want('window'), want('front')]),
      ch('gus20', 'Gus', 40, 'Mira row buddy', [want('aisle'), beside('mira20')]),
      ch('hal20', 'Hal', 120, 'Middle window rider', [want('window'), avoid('front'), avoid('back')]),
      ch('poppy20', 'Poppy', 320, 'Middle aisle rider', [want('aisle'), avoid('front'), avoid('back')]),
      ch('juno20', 'Juno', 260, 'Back window napper', [want('window'), want('back')]),
      ch('rex20', 'Rex', 20, 'Needs leg room', [want('legroom')]),
    ],
  },
  {
    id: 21, env: 'restaurant', title: 'Restaurant Rush', hostName: 'Chef Romeo',
    intro: 'Dinner service starts early tonight. Booth lovers, kitchen watchers, and music fans are all waving for attention.',
    outro: 'The rush turns graceful. Plates glide out, music hums, and everyone settles into the perfect dinner seat.',
    seats: restaurantLayout,
    characters: [
      ch('olive21', 'Olive', 120, 'Front window booth', [want('window'), want('quiet'), want('front')]),
      ch('theo21', 'Theo', 210, 'Quiet booth partner', [want('quiet'), beside('olive21')]),
      ch('basil21', 'Basil', 90, 'Kitchen view', [want('food'), avoid('aisle')]),
      ch('mina21', 'Mina', 300, 'Aisle foodie', [want('food'), want('aisle')]),
      ch('jazz21', 'Jazz', 30, 'Music in shade', [want('music'), avoid('sunlight')]),
      ch('sunny21', 'Sunny', 55, 'Sunny music table', [want('music'), want('sunlight')]),
    ],
  },
  {
    id: 22, env: 'classroom', title: 'Library Quiet Zone', hostName: 'Ms. Quill',
    intro: 'The classroom becomes a tiny library for reading hour. Everyone wants quiet pages, bright windows, or a steady desk.',
    outro: 'A hush falls over the room. Books open, pencils rest, and every reader has their perfect nook.',
    seats: classroomLayout,
    characters: [
      ch('page22', 'Page', 280, 'Front window reader', [want('front'), want('window')]),
      ch('quinn22', 'Quinn', 130, 'Middle front reader', [want('front'), avoid('window'), avoid('quiet')]),
      ch('rune22', 'Rune', 320, 'Quiet front reader', [want('front'), want('quiet')]),
      ch('lark22', 'Lark', 180, 'Back window reader', [want('back'), want('window')]),
      ch('midge22', 'Midge', 50, 'Middle back reader', [want('back'), avoid('window'), avoid('quiet')]),
      ch('sable22', 'Sable', 20, 'Quiet back reader', [want('back'), want('quiet')]),
    ],
  },
  {
    id: 23, env: 'airport', title: 'Airport Gate Shuffle', hostName: 'Gate Agent Joon',
    intro: 'Gate 18 changes again. Travelers split between window views, charger space, snack tables, and a little music.',
    outro: 'The boarding line forms calmly. Every traveler is close to exactly what they need.',
    seats: airportLayout,
    characters: [
      ch('ava23', 'Ava', 200, 'Quiet window flyer', [want('window'), want('quiet')]),
      ch('nico23', 'Nico', 330, 'Window seatmate', [want('window'), beside('ava23')]),
      ch('stretch23', 'Stretch', 30, 'Needs leg room', [want('legroom')]),
      ch('pia23', 'Pia', 150, 'Plain aisle seat', [want('aisle'), avoid('legroom')]),
      ch('bento23', 'Bento', 50, 'Snack without music', [want('food'), avoid('music')]),
      ch('lyric23', 'Lyric', 110, 'Snack and songs', [want('food'), want('music')]),
    ],
  },
  {
    id: 24, env: 'restaurant', title: 'Family Dinner Debate', hostName: 'Chef Romeo',
    intro: 'Family dinner is lively tonight. Keep the booth pair together, feed the hungry guests, and place the music lovers carefully.',
    outro: 'The table chatter turns warm. Everyone has room to laugh, eat, and enjoy the evening.',
    seats: restaurantLayout,
    characters: [
      ch('gran24', 'Gran', 340, 'Front quiet booth', [want('window'), want('quiet'), want('front')]),
      ch('uncle24', 'Uncle Mo', 210, 'Gran booth buddy', [want('quiet'), beside('gran24')]),
      ch('kid24', 'Kiddo', 30, 'Food but no aisle', [want('food'), avoid('aisle')]),
      ch('aunt24', 'Aunt Vi', 90, 'Aisle foodie', [want('food'), want('aisle')]),
      ch('cousin24', 'Cousin Rae', 120, 'Music in shade', [want('music'), avoid('sunlight')]),
      ch('singer24', 'Singer Sol', 50, 'Bright music seat', [want('music'), want('sunlight')]),
    ],
  },
  {
    id: 25, env: 'theater', title: 'Theater Seat Shuffle', hostName: 'Usher Pip',
    intro: 'A sold-out matinee means every seat matters. Aisle seekers, popcorn holders, and front-row fans need careful sorting.',
    outro: 'The curtains rise on a perfectly seated crowd. Even the popcorn tastes calmer.',
    seats: theaterLayout,
    characters: [
      ch('ash25', 'Ash', 120, 'Front aisle seat', [want('front'), want('aisle')]),
      ch('bea25', 'Bea', 320, 'Beside Ash up front', [want('front'), beside('ash25')]),
      ch('cato25', 'Cato', 210, 'Front away from Ash', [want('front'), notNear('ash25')]),
      ch('dex25', 'Dex', 250, 'Back aisle seat', [want('back'), want('aisle')]),
      ch('elle25', 'Elle', 190, 'Quiet middle back', [want('back'), want('quiet'), avoid('aisle'), avoid('food')]),
      ch('finn25', 'Finn', 30, 'Popcorn in back', [want('food')]),
    ],
  },
  {
    id: 26, env: 'wedding', title: 'Park Bench Mix-Up', hostName: 'Planner Posy',
    intro: 'The garden benches are arranged for photos. Window views, music, sunshine, and snacks all pull guests in different directions.',
    outro: 'The garden glows, cameras click, and the whole group looks picture-perfect.',
    seats: weddingLayout,
    characters: [
      ch('wren26', 'Wren', 150, 'Quiet garden view', [want('window'), want('quiet')]),
      ch('moss26', 'Moss', 90, 'Wren bench buddy', [want('quiet'), beside('wren26')]),
      ch('piper26', 'Piper', 300, 'Music in shade', [want('music'), avoid('sunlight')]),
      ch('sunny26', 'Sunny', 45, 'Sunny music spot', [want('music'), want('sunlight')]),
      ch('nia26', 'Nia', 210, 'Front snack table', [want('food'), want('front')]),
      ch('finn26', 'Finn', 20, 'Back snack table', [want('food'), want('back')]),
    ],
  },
  {
    id: 27, env: 'cruise', title: 'Cruise Deck Shuffle', hostName: 'Captain Coral',
    intro: 'The deck chairs are claimed fast. Ocean watchers, snack dancers, and quiet loungers need a fair arrangement.',
    outro: 'The deck settles into a breezy rhythm. Every chair catches the right bit of sea air.',
    seats: cruiseLayout,
    characters: [
      ch('azul27', 'Azul', 200, 'Sunny ocean chair', [want('window'), want('sunlight')]),
      ch('pearl27', 'Pearl', 330, 'Shady ocean chair', [want('window'), avoid('sunlight')]),
      ch('dj27', 'DJ', 110, 'Music only', [want('music'), avoid('food')]),
      ch('reef27', 'Reef', 30, 'Music and snacks', [want('music'), want('food')]),
      ch('calm27', 'Calm', 280, 'Front quiet lounger', [want('quiet'), want('front')]),
      ch('luna27', 'Luna', 150, 'Back quiet lounger', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 28, env: 'classroom', title: 'Classroom Partner Problem', hostName: 'Ms. Quill',
    intro: 'Partner work begins in five minutes. Some students must sit together, while others need the quietest desks.',
    outro: 'Partners pair up, notebooks open, and the whole room gets to work without a fuss.',
    seats: classroomLayout,
    characters: [
      ch('ella28', 'Ella', 280, 'Front window partner', [want('front'), want('window')]),
      ch('omar28', 'Omar', 130, 'Beside Ella', [want('front'), beside('ella28')]),
      ch('zoe28', 'Zoe', 320, 'Quiet front desk', [want('front'), want('quiet')]),
      ch('nina28', 'Nina', 180, 'Back window partner', [want('back'), want('window')]),
      ch('pip28', 'Pip', 50, 'Beside Nina', [want('back'), beside('nina28'), avoid('quiet')]),
      ch('rex28', 'Rex', 20, 'Quiet back desk', [want('back'), want('quiet')]),
    ],
  },
  {
    id: 29, env: 'bus', title: 'Rainy Bus Ride', hostName: 'Driver Dot',
    intro: 'Rain streaks the windows and everyone is carrying bags. Keep buddies close and give the tired riders their preferred seats.',
    outro: 'Wipers swish, seats settle, and the rainy ride feels almost cozy.',
    seats: busLayout,
    characters: [
      ch('rain29', 'Rain', 200, 'Front window watcher', [want('window'), want('front')]),
      ch('dash29', 'Dash', 30, 'Rain row buddy', [want('aisle'), beside('rain29')]),
      ch('mist29', 'Mist', 150, 'Middle window view', [want('window'), avoid('front'), avoid('back')]),
      ch('umbra29', 'Umbra', 270, 'Middle aisle seat', [want('aisle'), avoid('front'), avoid('back')]),
      ch('cozy29', 'Cozy', 330, 'Back window nap', [want('window'), want('back')]),
      ch('tall29', 'Tallulah', 70, 'Leg room in back', [want('legroom')]),
    ],
  },
  {
    id: 30, env: 'coffee', title: 'Cafe Study Group', hostName: 'Barista Bea',
    intro: 'Finals week fills the cafe. Study partners, quiet corners, and snack-powered musicians all need sorting.',
    outro: 'Highlighters glide, mugs steam, and the whole study group finally gets focused.',
    seats: coffeeLayout,
    characters: [
      ch('sola30', 'Sola', 45, 'Sunlit window notes', [want('window'), want('sunlight')]),
      ch('ink30', 'Ink', 210, 'Shady window notes', [want('window'), avoid('sunlight')]),
      ch('beat30', 'Beat', 120, 'Front music table', [want('music'), want('front')]),
      ch('snack30', 'Snack', 20, 'Back snack table', [want('food'), want('back')]),
      ch('hush30', 'Hush', 280, 'Front quiet table', [want('quiet'), want('front')]),
      ch('nook30', 'Nook', 330, 'Back quiet table', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 31, env: 'airport', title: 'Holiday Travel Rush', hostName: 'Gate Agent Joon',
    intro: 'The premium holiday chapter begins with a packed gate, heavy luggage, and travelers who know exactly what helps them relax.',
    outro: 'The gate sparkles with relief. Every traveler boards with a little holiday cheer.',
    seats: airportLayout,
    characters: [
      ch('clove31', 'Clove', 200, 'Quiet window flyer', [want('window'), want('quiet')]),
      ch('tinsel31', 'Tinsel', 330, 'Window travel buddy', [want('window'), beside('clove31')]),
      ch('atlas31', 'Atlas', 30, 'Leg room planner', [want('legroom')]),
      ch('ribbon31', 'Ribbon', 150, 'Aisle but not roomy', [want('aisle'), avoid('legroom')]),
      ch('cocoa31', 'Cocoa', 50, 'Snack no songs', [want('food'), avoid('music')]),
      ch('carol31', 'Carol', 110, 'Snack and songs', [want('food'), want('music')]),
    ],
  },
  {
    id: 32, env: 'classroom', title: 'Doctor Office Waiting Room', hostName: 'Nurse Nia',
    intro: 'The waiting room is using classroom chairs today. Quiet patients, window watchers, and paperwork helpers need calm seats.',
    outro: 'Clipboards settle, the room quiets, and every patient waits comfortably.',
    seats: classroomLayout,
    characters: [
      ch('marn32', 'Marn', 280, 'Front window patient', [want('front'), want('window')]),
      ch('clerk32', 'Clerk', 130, 'Front paperwork seat', [want('front'), avoid('window'), avoid('quiet')]),
      ch('hush32', 'Hush', 320, 'Quiet front patient', [want('front'), want('quiet')]),
      ch('opal32', 'Opal', 180, 'Back window patient', [want('back'), want('window')]),
      ch('milo32', 'Milo', 50, 'Back middle chair', [want('back'), avoid('window'), avoid('quiet')]),
      ch('sage32', 'Sage', 20, 'Quiet back patient', [want('back'), want('quiet')]),
    ],
  },
  {
    id: 33, env: 'cruise', title: 'Beach Chair Battle', hostName: 'Captain Coral',
    intro: 'A shore-day crowd takes over the deck chairs. Sun seekers, shade seekers, music fans, and quiet readers all stake a claim.',
    outro: 'Towels unfold, waves glitter, and every beach chair finally feels fair.',
    seats: cruiseLayout,
    characters: [
      ch('coral33', 'Coral', 45, 'Sunny ocean chair', [want('window'), want('sunlight')]),
      ch('drift33', 'Drift', 210, 'Shady ocean chair', [want('window'), avoid('sunlight')]),
      ch('marimba33', 'Marimba', 120, 'Music no snacks', [want('music'), avoid('food')]),
      ch('taco33', 'Taco', 20, 'Music and snacks', [want('music'), want('food')]),
      ch('novel33', 'Novel', 280, 'Front quiet read', [want('quiet'), want('front')]),
      ch('shade33', 'Shade', 330, 'Back quiet read', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 34, env: 'restaurant', title: 'First Date Seating', hostName: 'Chef Romeo',
    intro: 'First dates, double dates, and one solo foodie arrive at once. Keep the mood charming and the seats intentional.',
    outro: 'Candles glow and conversation flows. Every date gets just the right amount of sparkle.',
    seats: restaurantLayout,
    characters: [
      ch('ruby34', 'Ruby', 340, 'Front romantic booth', [want('window'), want('quiet'), want('front')]),
      ch('noah34', 'Noah', 210, 'Ruby booth date', [want('quiet'), beside('ruby34')]),
      ch('chef34', 'Chef Fan', 90, 'Food without aisle', [want('food'), avoid('aisle')]),
      ch('host34', 'Host Pal', 30, 'Aisle food seat', [want('food'), want('aisle')]),
      ch('lyra34', 'Lyra', 120, 'Music in shade', [want('music'), avoid('sunlight')]),
      ch('dawn34', 'Dawn', 50, 'Bright music table', [want('music'), want('sunlight')]),
    ],
  },
  {
    id: 35, env: 'coffee', title: 'Coffee Shop Encore', hostName: 'Barista Bea',
    intro: 'The Cozy Bean hosts an evening open mic. Study guests and performers need a careful split between quiet and music.',
    outro: 'The mic warms up, notebooks close, and every corner of the cafe feels chosen.',
    seats: coffeeLayout,
    characters: [
      ch('glow35', 'Glow', 45, 'Sunlit window seat', [want('window'), want('sunlight')]),
      ch('shade35', 'Shade', 210, 'Shady window seat', [want('window'), avoid('sunlight')]),
      ch('verse35', 'Verse', 120, 'Front music seat', [want('music'), want('front')]),
      ch('crumb35', 'Crumb', 20, 'Back snack seat', [want('food'), want('back')]),
      ch('quiet35', 'Quiet', 280, 'Front quiet seat', [want('quiet'), want('front')]),
      ch('nook35', 'Nook', 330, 'Back quiet seat', [want('quiet'), want('back')]),
    ],
  },
  {
    id: 36, env: 'theater', title: 'Movie Night Encore', hostName: 'Usher Pip',
    intro: 'The late show is trickier. Friends want to sit near each other, popcorn needs the back, and aisle seats are claimed fast.',
    outro: 'The projector flickers on. Every guest leans back exactly where they hoped to be.',
    seats: theaterLayout,
    characters: [
      ch('exit36', 'Exit', 120, 'Front aisle fan', [want('front'), want('aisle')]),
      ch('buddy36', 'Buddy', 320, 'Beside Exit', [want('front'), beside('exit36')]),
      ch('solo36', 'Solo', 210, 'Front away from Exit', [want('front'), notNear('exit36')]),
      ch('back36', 'Backbeat', 250, 'Back aisle fan', [want('back'), want('aisle')]),
      ch('calm36', 'Calm', 190, 'Quiet middle back', [want('back'), want('quiet'), avoid('aisle'), avoid('food')]),
      ch('pop36', 'Pop', 30, 'Back popcorn seat', [want('food')]),
    ],
  },
  {
    id: 37, env: 'wedding', title: 'Reception Encore Drama', hostName: 'Planner Posy',
    intro: 'The premium reception has one more seating puzzle. Garden guests, dancers, and cake lovers all need tact.',
    outro: 'The toast lands beautifully. No feuds, no fuss, just a glowing dance floor.',
    seats: weddingLayout,
    characters: [
      ch('ivy37', 'Ivy', 150, 'Quiet garden table', [want('window'), want('quiet')]),
      ch('fern37', 'Fern', 90, 'Garden partner', [want('quiet'), beside('ivy37')]),
      ch('waltz37', 'Waltz', 300, 'Music in shade', [want('music'), avoid('sunlight')]),
      ch('glint37', 'Glint', 45, 'Sunny music table', [want('music'), want('sunlight')]),
      ch('cake37', 'Cake', 210, 'Front cake seat', [want('food'), want('front')]),
      ch('toast37', 'Toast', 20, 'Back cake seat', [want('food'), want('back')]),
    ],
  },
  {
    id: 38, env: 'bus', title: 'Midnight Bus Puzzle', hostName: 'Driver Dot',
    intro: 'A midnight route rolls through glittering streets. Sleepy riders need windows, aisles, and a little extra room.',
    outro: 'Streetlights drift by as everyone settles in for the quiet ride home.',
    seats: busLayout,
    characters: [
      ch('nova38', 'Nova', 200, 'Front window seat', [want('window'), want('front')]),
      ch('orbit38', 'Orbit', 30, 'Nova aisle buddy', [want('aisle'), beside('nova38')]),
      ch('moth38', 'Moth', 150, 'Middle window seat', [want('window'), avoid('front'), avoid('back')]),
      ch('lane38', 'Lane', 270, 'Middle aisle seat', [want('aisle'), avoid('front'), avoid('back')]),
      ch('doze38', 'Doze', 330, 'Back window seat', [want('window'), want('back')]),
      ch('stride38', 'Stride', 70, 'Back leg room', [want('legroom')]),
    ],
  },
  {
    id: 39, env: 'cruise', title: 'Full Adventure Finale', hostName: 'Captain Coral',
    intro: 'The final premium preview gathers the trickiest guests on deck: ocean dreamers, music fans, snack hunters, and quiet stargazers.',
    outro: 'The whole ship cheers. Every clue clicks into place, and the full adventure feels wide open.',
    seats: cruiseLayout,
    characters: [
      ch('sun39', 'Sun', 45, 'Sunny ocean view', [want('window'), want('sunlight')]),
      ch('moon39', 'Moon', 210, 'Shady ocean view', [want('window'), avoid('sunlight')]),
      ch('song39', 'Song', 120, 'Music no buffet', [want('music'), avoid('food')]),
      ch('feast39', 'Feast', 20, 'Music buffet seat', [want('music'), want('food')]),
      ch('star39', 'Star', 280, 'Front quiet stars', [want('quiet'), want('front')]),
      ch('drift39', 'Drift', 330, 'Back quiet stars', [want('quiet'), want('back')]),
    ],
  },
];

export const LEVELS: Level[] = [
  ...BASE_LEVELS.slice(0, 5),
  ...rebalanceStoryLevels(BASE_LEVELS.slice(5)),
  ...EXPANSION_LEVELS,
];

export function levelById(id: number): Level | undefined {
  return LEVELS.find((l) => l.id === id);
}
